### ISSUE TITLE
Google Chrome support

### ISSUE THREAD

**Issue by dukeofgaming** [binaryage/xrefresh#17]
Now that Chrome supports extensions, would this be possible?.

**Comment by darwin** [comment]
Oh boy. Anything is possible when one has idea to change the world and executes.

I have [some plans](http://blog.binaryage.com/xrefresh-future-direction), but this has 0 priority right now, because I'm still debugging in Firebug and don't develop actively in Chrome. But the time comes.

**Comment by NV** [comment]
darwin, can you write up about how xrefresh protocol works? Maybe I could do something with Chrome.

**Comment by darwin** [comment]
well I don't want to invest time into describing the protocol, I think it pretty simple to read if from sources:

http://github.com/darwin/xrefresh-server
http://github.com/darwin/xrefresh

look at:
http://github.com/darwin/xrefresh-server/blob/master/lib/xrefresh-server/client.rb
http://github.com/darwin/xrefresh-server/blob/master/lib/xrefresh-server/server.rb

you have 2 reference client implementations (Firefox, IE) and 2 server implementations (OSX, Win).

---

Unfortunately XRefresh protocol is not well designed. Originally it started as a text stream over TCP connection. So  it is a stream of UTF-8 encoded JSONs separated by a known separator (like in MIME). JSON is simply `command` and `params` hash.

**Comment by NV** [comment]
Maybe it's stupid question, but how can I get JSON in the browser? I mean, if I open http://127.0.0.1:41258/ I'll see nothing.

**Comment by darwin** [comment]
Well you may modify Firefox extension or ruby server to print it somewhere into log console. You may also use some system level socket sniffer, like WireShark. This TCP connection is not managed by the browser. It is created separately by the extension.

**Comment by NV** [comment]
Oh, I know about `nc 127.0.0.1 41258`, I don't know how to handle raw TCP in the browser (not just Firefox extension).

So I need HTTP or WebSockets server. I'll try to do something, but I'm a totally newbie to all that stuff.

**Comment by NV** [comment]
[XRefresh for Chrome](http://gist.github.com/342682). First working version. Very cheesy.

My ruby script uses a WebSockets, which works only in Chrome. Original xrefresh-server uses a raw TCP, which works in Firefox extension. [mish](http://github.com/melito/mish) uses raw TCP too and works in Safari. Neither of them works in Opera.

I think we need ultimate xrefresh-server which could work with all major browsers. I don't know how to implement it. Maybe it should use HTTP with long polling. Any thoughts?

**Comment by darwin** [comment]
Nice work! 

I think WebSockets is the future way to go. And small javascript driver code included directly in the page. No extensions at all.

**Comment by NV** [comment]
darwin,
Hey, it's possible to implement WebSockets in Firefox extensions! We have got TCP sockets, so we can implement WebSockets on top of it, isn't it?

**Comment by darwin** [comment]
NV, I'm not going to invest my time into emulating WebSockets in a Firefox extension. I'd wait for Mozilla guys to do so :-)

**Comment by NV** [comment]
darwin, reasonable answer :-)

**Comment by darwin** [comment]
Btw. it is being worked on:
https://bugzilla.mozilla.org/show_bug.cgi?id=472529

**Comment by NV** [comment]
Yeah, I subscribed.

**Comment by NV** [comment]
If someone would like to see XRefresh for Chrome working with `file://` scheme please star the [bug 31947](http://code.google.com/p/chromium/issues/detail?id=31947).

**Comment by dukeofgaming** [comment]
Starred

**Comment by NV** [comment]
[LiveReload](http://github.com/mockko/livereload). It looks much more solid than my http://gist.github.com/342682
