### ISSUE TITLE
xrefresh Firefox plugin missing

### ISSUE THREAD

**Issue by krisleech** [binaryage/xrefresh#26]
It appears the firefox plugin has gone, or at least the link is broken: http://addons.mozilla.org/en-US/firefox/addon/7711/

**Comment by darwin** [comment]
yes, they removed all non-approved addons and I have absolutely no time to push it through their approval process, this would need some rewrites

but still I have plan to do it someday

**Comment by krisleech** [comment]
Is there an alternative URL it can be downloaded from or can Firefox only install from mozilla.org?

**Comment by darwin** [comment]
https://github.com/downloads/darwin/xrefresh/xrefresh-1.5.xpi

On Thu, Apr 7, 2011 at 4:11 PM, krisleech
reply@reply.github.com
wrote:

**Comment by krisleech** [comment]
Fantastic, thanks, might be worth updating the link on the website to point there.
