### ISSUE TITLE
OSX Installation Errors

### ISSUE THREAD

**Issue by ryonlife** [binaryage/xrefresh#5]
When following the installation instructions at http://xrefresh.binaryage.com/#osx, I get the following error when trying to run xrefresh-server for the first time:

/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50: [BUG] Segmentation fault
ruby 1.8.6 (2008-08-11) [universal-darwin9.0]
Abort trap

I am running these versions:

OS X 10.5.7
Firefox 3.5
Firebug 1.4.2
XRefresh 1.2
Ruby 1.8.6
Ruby Cocoa 1.0.0

Any ideas what the problem is?

**Comment by darwin** [comment]
Problem is in new RubyCocoa, try this:
http://gist.github.com/158851

**Comment by ryonlife** [comment]
Awesome. Thanks.

**Comment by 01iv3r** [comment]
I still get the following error when trying to install xrefresh-server:

ojs:~ ilo$ sudo gem install xrefresh-server
Bulk updating Gem source index for: http://gems.rubyforge.org
Building native extensions.  This could take a while...
ERROR:  Error installing xrefresh-server:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb install xrefresh-server
can't find header files for ruby.

Gem files will remain installed in /Library/Ruby/Gems/1.8/gems/json-1.1.9 for inspection.
Results logged to /Library/Ruby/Gems/1.8/gems/json-1.1.9/ext/json/ext/generator/gem_make.out

**Comment by darwin** [comment]
featherodd: your error is not related to xrefresh-server, but json-1.1.9 gem compilation

try `sudo gem install json` separately and resolve that issue before retrying installing xrefresh-server gem

**Comment by 01iv3r** [comment]
Bulk updating Gem source index for: http://gems.rubyforge.org
Bulk updating Gem source index for: http://gems.github.com
Building native extensions.  This could take a while...
ERROR:  Error installing json:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb install json
can't find header files for ruby.

Gem files will remain installed in /Library/Ruby/Gems/1.8/gems/json-1.1.9 for inspection.
Results logged to /Library/Ruby/Gems/1.8/gems/json-1.1.9/ext/json/ext/generator/gem_make.out

**Comment by darwin** [comment]
you don't have ruby header files on expected paths, your configuration is messed up

**Comment by janogarcia** [comment]
I had the same issue as featherodd. Just installed Xcode from Snow Leopard DVD as suggested in [Missing Ruby headers after Snow Leopard upgrade](http://www.fngtps.com/2009/08/missing-ruby-headers-after-snow-leopard-upgrade) and `sudo gem install xrefresh-server` worked properly again.
