### ISSUE TITLE
no connection on local VH

### ISSUE THREAD

**Issue by phpwalter** [binaryage/xrefresh#6]
I have an XP Pro SP3
Apache/2.2.11 (Win32) PHP/5.2.8 
Firefox 3.5
Firebug 1.4.2

I can't get this extension to work via local virtual hosts.

I don't use LOCALHOST. Each of my domains are reflected locally, for development, as a local VH.

Any ideas?

Thx

Walter

**Comment by darwin** [comment]
Both extension and monitor have possiblity to set HOST and PORT. So you should be able to setup it.

In FF extension go to URL: `config:about` and look for `extensions.xrefresh.host` and `extensions.xrefresh.port`

**Comment by phpwalter** [comment]
thanks for the clue.

I had to place '127.0.0.1' in the HOST field of the browser config:about to make my virtual domains work. THen I had to "connect" to each one individually as well.

Thx for your help

**Comment by darwin** [comment]
note to me:
this is second person having problem with localhost, generally it is not good idea to remove it from etc/hosts, but some people do.

in 0.7 replace default values from "localhost" to "127.0.0.1" to make it safer
ref: http://github.com/darwin/xrefresh/blob/7e4fa68cd5b21cc00926b66e7170061886c58488/src/firefox/defaults/preferences/xrefresh.js#L9

**Comment by phpwalter** [comment]
I did not remove localhost form the etc/hosts file, it is still there as are referencex to my local virtual hosts.

**Comment by darwin** [comment]
ok, so in etc/hosts you've modified localhost to resolve to some other IP than 127.0.0.1, right?

**Comment by phpwalter** [comment]
nope. This is part of my etc/hosts file...

127.0.0.1       localhost
127.0.0.1       activate.adobe.com
127.0.0.1       phpMyAdmin
127.0.0.1       phpDoc
127.0.0.1       php.test
127.0.0.1       jsclasses

**Comment by darwin** [comment]
so why localhost didn't work for you in xrefresh.host? according to your etc/hosts it is same as 127.0.0.1

**Comment by phpwalter** [comment]
yea, that's the question. ;)

**Comment by darwin** [comment]
Have you solved this issue?
I'm closing it because it is probably on your side. Reopen at will.
