### ISSUE TITLE
Programm crashs when selecting Type

### ISSUE THREAD

**Issue by Ninerian** [binaryage/xrefresh#7]
Hello when I add an folder and want to change the type from generic to another the programm crashs.
Als It doesnt refresh my firefox, the returning message is;

Unable to parse server JSON message: {"date":"21.08.2009","time":"14:21:23","root":"P:\Web\Daniel_Übung\mootorial_day1","name":"Mootorial","type":null,"files":[{"action":"changed","path1":"index.html","path2":""}],"contents":{},"command":"DoRefresh"

Hope this will help

**Comment by Ninerian** [comment]
I use Windows Vista 64 and Firefox, also e as editor.

**Comment by darwin** [comment]
fixed in v1.3
